#!/bin/bash

# Check if Homebrew is installed
if ! command -v brew >/dev/null 2>&1; then
  echo "Homebrew is not installed. Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/main/install.sh)"
else
  echo "Homebrew is already installed."
fi

# Install diff-so-fancy if not already installed
if ! brew list -1 | grep -q "^diff-so-fancy\$"; then
  echo "diff-so-fancy is not installed. Installing..."
  brew install diff-so-fancy
else
  echo "diff-so-fancy is already installed."
fi

# Install rectangle if not already installed
if ! brew list -1 | grep -q "^rectangle\$"; then
  echo "rectangle is not installed. Installing..."
  brew install rectangle
else
  echo "rectangle is already installed."
fi

install_fzf() {
  echo "Checking if fzf is already installed"
  if [ ! $(command -v fzf) ]; then
    echo "Installing fzf"
    export NONINTERACTIVE=1
    brew install fzf
    $(brew --prefix)/opt/fzf/install
  else
    echo "fzf is already installed"
  fi
}
install_fzf

# Install https://github.com/magicmonty/bash-git-prompt
echo "Checking if bash-git-prompt installed"
if [ ! -d ~/.bash-git-prompt ]; then
  echo "Installing bash-git-prompt"
  git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1
  if ! grep -q "source $HOME/.bash-git-prompt/gitprompt.sh" ~/.bash_profile; then
    echo "GIT_PROMPT_ONLY_IN_REPO=0" >> ~/.bash_profile
    echo "source $HOME/.bash-git-prompt/gitprompt.sh" >> ~/.bash_profile
  fi
else
  echo "bash-git-prompt already installed"
fi


# Install VSCode extensions
cat ${HOME}/vscode/extensions.txt | xargs -L 1 code --install-extension

# Make autocomplete case insensitive 
# If ~/.inputrc doesn't exist yet: First include the original /etc/inputrc
# so it won't get overriden
if [ ! -a ~/.inputrc ]; then echo '$include /etc/inputrc' > ~/.inputrc; fi
# Add shell-option to ~/.inputrc to enable case-insensitive tab completion
grep -q "set completion-ignore-case On" ~/.inputrc || echo "set completion-ignore-case On" >> ~/.inputrc

echo "Boostrap completed"
